In [55]:
import numpy as np
import numba as nb


def matrix_maker(y):
    matrix = np.zeros((len(y_input)//4,4))
    
    for i in range(matrix.shape[0]):
        for j in range(4):
            matrix[i,j]= y_input[4*i+j]
    return matrix


def array_maker(M):
    array = np.zeros(len(y_input))
    
    for i in range(matrix.shape[0]):
        for j in range(4):
            array[4*i+j] = M[i,j]
    return array

In [58]:
y_input = np.arange(24)
matrix = matrix_maker(y_input)

array = array_maker(matrix)

In [59]:
print(matrix)
print(array)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]
 [12. 13. 14. 15.]
 [16. 17. 18. 19.]
 [20. 21. 22. 23.]]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23.]
